# Generated by Django 2.1.7 on 2019-05-02 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_posted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
