# Generated by Django 2.1.7 on 2019-05-02 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_time_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_posted',
            field=models.TimeField(auto_now=django.utils.timezone.now),
        ),
    ]
