# Generated by Django 2.1.7 on 2019-05-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190502_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time_posted',
        ),
    ]
